<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="metodo" type="metodoType"/>
	<xs:complexType name="metodoType">
		<xs:choice>
			<xs:element type="iniciarType" name="iniciar"/>
			<xs:element type="obterType" name="obter"/>
			<xs:element type="jogarType" name="jogar"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="iniciarType">
		<xs:attribute type="xs:string" name="nickname" use="required"/>
		<xs:attribute type="xs:string" name="senha" use="required"/>
	</xs:complexType>
	<xs:complexType name="obterType"/>
	<xs:complexType name="jogarType">
		<xs:attribute type="jogadaType" name="jogada" use="required"/>
	</xs:complexType>
	<xs:simpleType name="jogadaType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]+ [0-9]+ [0-9]+ [0-9]+" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>